# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: f47ff619519c4c410d32da2f3f75e906e1568c81f9856ebd4f5f243875be363311ef0a3ca37078deaca9f57253abf22b6a739d5b8fecd1faa7b9ae77b07fbd72

test:
  secret_key_base: b2f040870cce24679f36200871518d4d7e23d9e171cd69c293a635abbda0eff26ab0d11115f8964546a356f2601a7a260734531f6b741cf1a0af1d8aa9f963f9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
